FORMAT: 1A
HOST: https://isaac.jamesmcfadden.co.uk/api/v1

# Binding of Isaac API

Documentation for the Open Source Binding of Isaac RESTful API.

The source code is hosted at [https://github.com/jamesmcfadden/binding-of-isaac-api](https://github.com/jamesmcfadden/binding-of-isaac-api).

**Note that the API is still in early development, so breaking changes can, and most likely will, happen.**

## Bosses [/boss]

### List all Bosses [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":83,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=2",
            "data":[  
                {  
                    "id":"xWPxL",
                    "name":"Blastocyst",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/xWPxL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/xwpxl.png"
                },
                {  
                    "id":"3ot7Z",
                    "name":"Blue Baby",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/3ot7Z",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/3ot7z.png"
                },
                {  
                    "id":"iK4uM",
                    "name":"Brownie",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/iK4uM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ik4um.png"
                },
                {  
                    "id":"Rty6q",
                    "name":"C.H.A.D.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Rty6q",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/rty6q.png"
                },
                {  
                    "id":"pfj4n",
                    "name":"Chub",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/pfj4n",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/pfj4n.png"
                },
                {  
                    "id":"YaF7j",
                    "name":"Conquest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/YaF7j",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/yaf7j.png"
                },
                {  
                    "id":"ry7Ua",
                    "name":"Daddy Long Legs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/ry7Ua",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ry7ua.png"
                },
                {  
                    "id":"ufpUE",
                    "name":"Dangle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/ufpUE",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ufpue.png"
                },
                {  
                    "id":"YaGZp",
                    "name":"Dark One",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/YaGZp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/yagzp.png"
                },
                {  
                    "id":"LMCDe",
                    "name":"Death",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/LMCDe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/lmcde.png"
                },
                {  
                    "id":"gs6UX",
                    "name":"Dingle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/gs6UX",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gs6ux.png"
                },
                {  
                    "id":"plQUT",
                    "name":"Envy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/plQUT",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/plqut.png"
                },
                {  
                    "id":"Bzoer",
                    "name":"Famine",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Bzoer",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bzoer.png"
                },
                {  
                    "id":"p7mbN",
                    "name":"Fistula",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/p7mbN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/p7mbn.png"
                },
                {  
                    "id":"gZVST",
                    "name":"Gabriel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/gZVST",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gzvst.png"
                },
                {  
                    "id":"7GFNZ",
                    "name":"Gemini",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/7GFNZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/7gfnz.png"
                },
                {  
                    "id":"mLE6V",
                    "name":"Gish",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/mLE6V",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/mle6v.png"
                },
                {  
                    "id":"vuKDM",
                    "name":"Gluttony",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/vuKDM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/vukdm.png"
                },
                {  
                    "id":"Jv6Mk",
                    "name":"Greed",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Jv6Mk",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/jv6mk.png"
                },
                {  
                    "id":"N6WWA",
                    "name":"Gurdy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/N6WWA",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/n6wwa.png"
                },
                {  
                    "id":"mFJUH",
                    "name":"Gurdy Jr.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/mFJUH",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/mfjuh.png"
                },
                {  
                    "id":"yKfJS",
                    "name":"Gurglings",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/yKfJS",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ykfjs.png"
                },
                {  
                    "id":"KruQ8",
                    "name":"Hush",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/KruQ8",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/kruq8.png"
                },
                {  
                    "id":"F5Ta0",
                    "name":"Isaac",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/F5Ta0",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/f5ta0.png"
                },
                {  
                    "id":"PJ6Pl",
                    "name":"It Lives",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/PJ6Pl",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/pj6pl.png"
                },
                {  
                    "id":"VKq9n",
                    "name":"Krampus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/VKq9n",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/vkq9n.png"
                },
                {  
                    "id":"icZ0S",
                    "name":"Larry Jr.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/icZ0S",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/icz0s.png"
                },
                {  
                    "id":"AFvzN",
                    "name":"Little Horn",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/AFvzN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/afvzn.png"
                },
                {  
                    "id":"bG5Lf",
                    "name":"Loki",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/bG5Lf",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bg5lf.png"
                },
                {  
                    "id":"GJgId",
                    "name":"Lokii",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/GJgId",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gjgid.png"
                },
                {  
                    "id":"fv7EQ",
                    "name":"Lust",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/fv7EQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fv7eq.png"
                },
                {  
                    "id":"TOwix",
                    "name":"Mama Gurdy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/TOwix",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/towix.png"
                },
                {  
                    "id":"FHsB6",
                    "name":"Mask of Infamy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/FHsB6",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fhsb6.png"
                },
                {  
                    "id":"af31L",
                    "name":"Mega Fatty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/af31L",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/af31l.png"
                },
                {  
                    "id":"6m78r",
                    "name":"Mega Maw",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/6m78r",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/6m78r.png"
                },
                {  
                    "id":"i0vFD",
                    "name":"Mega Satan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/i0vFD",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/i0vfd.png"
                },
                {  
                    "id":"PHIeR",
                    "name":"Mom",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/PHIeR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/phier.png"
                },
                {  
                    "id":"BmmeN",
                    "name":"Mom's Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/BmmeN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bmmen.png"
                },
                {  
                    "id":"qVIN9",
                    "name":"Monstro",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/qVIN9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qvin9.png"
                },
                {  
                    "id":"TswBe",
                    "name":"Monstro II",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/TswBe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/tswbe.png"
                },
                {  
                    "id":"GA8TG",
                    "name":"Mr. Fred",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/GA8TG",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ga8tg.png"
                },
                {  
                    "id":"Ii7MK",
                    "name":"Peep",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Ii7MK",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ii7mk.png"
                },
                {  
                    "id":"twGCn",
                    "name":"Pestilence",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/twGCn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/twgcn.png"
                },
                {  
                    "id":"fa6Ly",
                    "name":"Pin",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/fa6Ly",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fa6ly.png"
                },
                {  
                    "id":"0ug2s",
                    "name":"Polycephalus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/0ug2s",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/0ug2s.png"
                },
                {  
                    "id":"banyC",
                    "name":"Pride",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/banyC",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/banyc.png"
                },
                {  
                    "id":"xjnFL",
                    "name":"Rag Man",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/xjnFL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/xjnfl.png"
                },
                {  
                    "id":"QkpIn",
                    "name":"Satan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/QkpIn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qkpin.png"
                },
                {  
                    "id":"qzFxM",
                    "name":"Scolex",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/qzFxM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qzfxm.png"
                },
                {  
                    "id":"bTCYd",
                    "name":"Sloth",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/bTCYd",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/btcyd.png"
                }
            ]
        }

### Retrieve a Boss [GET /boss/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"qVIN9",
                "name":"Monstro",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/qVIN9",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qVIN9.png"
            }

## Chapters [/chapters]

### List all Chapters [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":7,
            "total":7,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter?page=1",
            "next":null,
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter?page=1",
            "data":[  
                {  
                    "id":"VgNLa",
                    "name":"Chapter 1",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/VgNLa"
                },
                {  
                    "id":"On9K6",
                    "name":"Chapter 2",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/On9K6"
                },
                {  
                    "id":"8nSAJ",
                    "name":"Chapter 3",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/8nSAJ"
                },
                {  
                    "id":"WDRwO",
                    "name":"Chapter 4",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/WDRwO"
                },
                {  
                    "id":"9L0st",
                    "name":"Chapter 4.5",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/9L0st"
                },
                {  
                    "id":"zmJ0v",
                    "name":"Chapter 5",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/zmJ0v"
                },
                {  
                    "id":"6d7id",
                    "name":"Chapter 6",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/6d7id"
                }
            ]
        }

### Retrieve a Chapter [GET /chapter/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {  
                "id":"VgNLa",
                "name":"Chapter 1",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/VgNLa",
                "environments":[  
                    {  
                        "id":"g9yJM",
                        "name":"The Basement",
                        "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/g9yJM"
                    },
                    {  
                        "id":"HRej5",
                        "name":"The Cellar",
                        "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/HRej5"
                    },
                    {  
                        "id":"zPJZN",
                        "name":"Burning Basement",
                        "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/zPJZN"
                    }
                ]
            }

## Characters [/character]

### List all Characters [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":13,
            "total":13,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/character?page=1",
            "next":null,
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/character?page=1",
            "data":[  
                {  
                    "id":"RQEtH",
                    "name":"???",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/RQEtH",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/RQEtH.png"
                },
                {  
                    "id":"KNv0f",
                    "name":"Azazel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/KNv0f",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/KNv0f.png"
                },
                {  
                    "id":"9KvNB",
                    "name":"Cain",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/9KvNB",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/9KvNB.png"
                },
                {  
                    "id":"knhRS",
                    "name":"Eden",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/knhRS",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/knhRS.png"
                },
                {  
                    "id":"OO0AR",
                    "name":"Eve",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/OO0AR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/OO0AR.png"
                },
                {  
                    "id":"kyGxc",
                    "name":"Isaac",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/kyGxc",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/kyGxc.png"
                },
                {  
                    "id":"h1oAT",
                    "name":"Judas",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/h1oAT",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/h1oAT.png"
                },
                {  
                    "id":"fPLTc",
                    "name":"Keeper",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/fPLTc",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/fPLTc.png"
                },
                {  
                    "id":"i1Rug",
                    "name":"Lazarus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/i1Rug",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/i1Rug.png"
                },
                {  
                    "id":"W5V56",
                    "name":"Lilith",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/W5V56",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/W5V56.png"
                },
                {  
                    "id":"tkYZl",
                    "name":"Magdalene",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/tkYZl",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/tkYZl.png"
                },
                {  
                    "id":"WIDTF",
                    "name":"Samson",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/WIDTF",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/WIDTF.png"
                },
                {  
                    "id":"XXEjW",
                    "name":"The Lost",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/XXEjW",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/XXEjW.png"
                }
            ]
        }

### Retrieve a Character [GET /character/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"kyGxc",
                "name":"Isaac",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/character/kyGxc",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/characters/kyGxc.png"
            }

## Environments [/environment]

### List all Environments [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":17,
            "total":17,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/environment?page=1",
            "next":null,
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/environment?page=1",
            "data":[  
                {  
                    "id":"jgvTX",
                    "name":"Blue Womb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/jgvTX"
                },
                {  
                    "id":"zPJZN",
                    "name":"Burning Basement",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/zPJZN"
                },
                {  
                    "id":"oUhWp",
                    "name":"Cathedral",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/oUhWp"
                },
                {  
                    "id":"RTgYK",
                    "name":"Dank Depths",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/RTgYK"
                },
                {  
                    "id":"q3fpJ",
                    "name":"Dark Room",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/q3fpJ"
                },
                {  
                    "id":"JE9Ur",
                    "name":"Flooded Caves",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/JE9Ur"
                },
                {  
                    "id":"YC4Sl",
                    "name":"Necropolis",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/YC4Sl"
                },
                {  
                    "id":"zAIPN",
                    "name":"Scarred Womb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/zAIPN"
                },
                {  
                    "id":"e7NFa",
                    "name":"Sheol",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/e7NFa"
                },
                {  
                    "id":"g9yJM",
                    "name":"The Basement",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/g9yJM"
                },
                {  
                    "id":"eUOVP",
                    "name":"The Catacombs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/eUOVP"
                },
                {  
                    "id":"oNmdb",
                    "name":"The Caves",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/oNmdb"
                },
                {  
                    "id":"HRej5",
                    "name":"The Cellar",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/HRej5"
                },
                {  
                    "id":"eLU2G",
                    "name":"The Chest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/eLU2G"
                },
                {  
                    "id":"UDvZZ",
                    "name":"The Depths",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/UDvZZ"
                },
                {  
                    "id":"coTOZ",
                    "name":"The Womb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/coTOZ"
                },
                {  
                    "id":"xHnVN",
                    "name":"Utero",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/xHnVN"
                }
            ]
        }

### Retrieve an Environment [GET /environment/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"g9yJM",
                "name":"The Basement",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/environment/g9yJM",
                "chapter": {
                    "id":"VgNLa",
                    "name":"Chapter 1",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/chapter/VgNLa"
                }
            }

## Items [/item]

### List all Items [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":438,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=9",
            "data":[  
                {  
                    "id":"c12kq",
                    "name":"???'s Only Friend",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/c12kq",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/c12kq.png"
                },
                {  
                    "id":"gGBZ0",
                    "name":"<3",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/gGBZ0",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ggbz0.png"
                },
                {  
                    "id":"Fi7wn",
                    "name":"1up!",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/Fi7wn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fi7wn.png"
                },
                {  
                    "id":"5eMPp",
                    "name":"20/20",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/5eMPp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/5empp.png"
                },
                {  
                    "id":"xp9U9",
                    "name":"3 Dollar Bill",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/xp9U9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/xp9u9.png"
                },
                {  
                    "id":"y7NCo",
                    "name":"8 Inch Nails",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/y7NCo",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/y7nco.png"
                },
                {  
                    "id":"GGxkj",
                    "name":"9 Volt",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/GGxkj",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ggxkj.png"
                },
                {  
                    "id":"YHhYP",
                    "name":"A Dollar",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/YHhYP",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/yhhyp.png"
                },
                {  
                    "id":"pYWTI",
                    "name":"A Lump Of Coal",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/pYWTI",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/pywti.png"
                },
                {  
                    "id":"fXgdx",
                    "name":"A Quarter",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fXgdx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fxgdx.png"
                },
                {  
                    "id":"CraPZ",
                    "name":"A Snack",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/CraPZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/crapz.png"
                },
                {  
                    "id":"wvkEw",
                    "name":"Abaddon",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/wvkEw",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wvkew.png"
                },
                {  
                    "id":"TGsYa",
                    "name":"Abel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/TGsYa",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/tgsya.png"
                },
                {  
                    "id":"hz3cQ",
                    "name":"Anarchist Cookbook",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/hz3cQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hz3cq.png"
                },
                {  
                    "id":"eOTdf",
                    "name":"Anemic",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/eOTdf",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/eotdf.png"
                },
                {  
                    "id":"iUbbQ",
                    "name":"Ankh",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/iUbbQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/iubbq.png"
                },
                {  
                    "id":"iSdFu",
                    "name":"Anti-Gravity",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/iSdFu",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/isdfu.png"
                },
                {  
                    "id":"On84I",
                    "name":"Aquarius",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/On84I",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/on84i.png"
                },
                {  
                    "id":"rEky9",
                    "name":"Aries",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/rEky9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/reky9.png"
                },
                {  
                    "id":"D9B0M",
                    "name":"Athame",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/D9B0M",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/d9b0m.png"
                },
                {  
                    "id":"KQnUV",
                    "name":"Ball Of Bandages",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/KQnUV",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/kqnuv.png"
                },
                {  
                    "id":"EmDst",
                    "name":"Ball Of Tar",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EmDst",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/emdst.png"
                },
                {  
                    "id":"l74LW",
                    "name":"BBF",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/l74LW",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/l74lw.png"
                },
                {  
                    "id":"IbtH7",
                    "name":"Best Bud",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/IbtH7",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ibth7.png"
                },
                {  
                    "id":"esTBU",
                    "name":"Best Friend",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/esTBU",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/estbu.png"
                },
                {  
                    "id":"o9S30",
                    "name":"Betrayal",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/o9S30",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/o9s30.png"
                },
                {  
                    "id":"EdMbD",
                    "name":"BFFS!",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EdMbD",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/edmbd.png"
                },
                {  
                    "id":"Eipw9",
                    "name":"Big Fan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/Eipw9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/eipw9.png"
                },
                {  
                    "id":"wyQgx",
                    "name":"Binky",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/wyQgx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wyqgx.png"
                },
                {  
                    "id":"UtVjO",
                    "name":"Black Candle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/UtVjO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/utvjo.png"
                },
                {  
                    "id":"jLia3",
                    "name":"Black Lotus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/jLia3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/jlia3.png"
                },
                {  
                    "id":"xmxnZ",
                    "name":"Black Powder",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/xmxnZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/xmxnz.png"
                },
                {  
                    "id":"B4Vbz",
                    "name":"Blank Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/B4Vbz",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/b4vbz.png"
                },
                {  
                    "id":"9haGF",
                    "name":"Blood Bag",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/9haGF",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/9hagf.png"
                },
                {  
                    "id":"c5PfF",
                    "name":"Blood Clot",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/c5PfF",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/c5pff.png"
                },
                {  
                    "id":"WMiun",
                    "name":"Blood Of The Martyr",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/WMiun",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wmiun.png"
                },
                {  
                    "id":"fPRsJ",
                    "name":"Blood Rights",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fPRsJ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fprsj.png"
                },
                {  
                    "id":"oxgoK",
                    "name":"Bloody Lust",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/oxgoK",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/oxgok.png"
                },
                {  
                    "id":"72Dht",
                    "name":"Blue Cap",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/72Dht",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/72dht.png"
                },
                {  
                    "id":"EhHkb",
                    "name":"Blue Map",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EhHkb",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ehhkb.png"
                },
                {  
                    "id":"HRJ8l",
                    "name":"Bob's Brain",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/HRJ8l",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hrj8l.png"
                },
                {  
                    "id":"DrwHN",
                    "name":"Bob's Curse",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/DrwHN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/drwhn.png"
                },
                {  
                    "id":"1quq3",
                    "name":"Bob's Rotten Head",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/1quq3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/1quq3.png"
                },
                {  
                    "id":"HlFtG",
                    "name":"Bobby-Bomb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/HlFtG",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hlftg.png"
                },
                {  
                    "id":"GBwDx",
                    "name":"Bogo Bombs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/GBwDx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/gbwdx.png"
                },
                {  
                    "id":"J71v7",
                    "name":"Bomb Bag",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/J71v7",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/j71v7.png"
                },
                {  
                    "id":"3W0mR",
                    "name":"Bomber Boy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/3W0mR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/3w0mr.png"
                },
                {  
                    "id":"fv4EL",
                    "name":"Book Of Revelations",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fv4EL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fv4el.png"
                },
                {  
                    "id":"LMCDe",
                    "name":"Book Of Secrets",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/LMCDe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/lmcde.png"
                },
                {  
                    "id":"KOPsZ",
                    "name":"Book Of Shadows",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/KOPsZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/kopsz.png"
                }
            ]
        }

### Retrieve an Item [GET /item/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"2JrEs",
                "name":"Pentagram",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/2JrEs",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/2jres.png"
            }

## Monsters [/monster]

### List all Monsters [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":167,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/monster?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/monster?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/monster?page=4",
            "data":[  
                {  
                    "id":"RsxKO",
                    "name":"Angelic Baby",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/RsxKO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/RsxKO.png"
                },
                {  
                    "id":"3ot7Z",
                    "name":"Attack Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/3ot7Z",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/3ot7Z.png"
                },
                {  
                    "id":"F5svt",
                    "name":"Baby",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/F5svt",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/F5svt.png"
                },
                {  
                    "id":"icZ0S",
                    "name":"Baby Long Legs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/icZ0S",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/icZ0S.png"
                },
                {  
                    "id":"bzWfN",
                    "name":"Begotten",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/bzWfN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/bzWfN.png"
                },
                {  
                    "id":"aaW0A",
                    "name":"Big Spider",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/aaW0A",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/aaW0A.png"
                },
                {  
                    "id":"5eMPp",
                    "name":"Black Bony",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/5eMPp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/5eMPp.png"
                },
                {  
                    "id":"xWPxL",
                    "name":"Black Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/xWPxL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/xWPxL.png"
                },
                {  
                    "id":"jLia3",
                    "name":"Black Globin",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/jLia3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/jLia3.png"
                },
                {  
                    "id":"Njgyo",
                    "name":"Black Globin's Body",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/Njgyo",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/Njgyo.png"
                },
                {  
                    "id":"yRTrQ",
                    "name":"Black Maw",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/yRTrQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/yRTrQ.png"
                },
                {  
                    "id":"TOwix",
                    "name":"Blind Creep",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/TOwix",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/TOwix.png"
                },
                {  
                    "id":"CaLD4",
                    "name":"Bloodshot Eye",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/CaLD4",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/CaLD4.png"
                },
                {  
                    "id":"EdMbD",
                    "name":"Blubber",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/EdMbD",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/EdMbD.png"
                },
                {  
                    "id":"PHIeR",
                    "name":"Blue Boil",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/PHIeR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/PHIeR.png"
                },
                {  
                    "id":"a2IHI",
                    "name":"Blue Conjoined Fatty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/a2IHI",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/a2IHI.png"
                },
                {  
                    "id":"nt5Hm",
                    "name":"Blue Gaper",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/nt5Hm",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/nt5Hm.png"
                },
                {  
                    "id":"af31L",
                    "name":"Boil",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/af31L",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/af31L.png"
                },
                {  
                    "id":"ROfws",
                    "name":"Bone Knight",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/ROfws",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/ROfws.png"
                },
                {  
                    "id":"BqZeT",
                    "name":"Bony",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/BqZeT",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/BqZeT.png"
                },
                {  
                    "id":"gs6UX",
                    "name":"Boom Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/gs6UX",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/gs6UX.png"
                },
                {  
                    "id":"AlE01",
                    "name":"Brain",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/AlE01",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/AlE01.png"
                },
                {  
                    "id":"ep7IU",
                    "name":"Brimstone Grimace",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/ep7IU",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/ep7IU.png"
                },
                {  
                    "id":"e7pWM",
                    "name":"Buttlicker",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/e7pWM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/e7pWM.png"
                },
                {  
                    "id":"FjIhO",
                    "name":"Camillo Jr.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/FjIhO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/FjIhO.png"
                },
                {  
                    "id":"hN0mz",
                    "name":"Charger",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/hN0mz",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/hN0mz.png"
                },
                {  
                    "id":"T2wH6",
                    "name":"Chubber",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/T2wH6",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/T2wH6.png"
                },
                {  
                    "id":"HRJ8l",
                    "name":"Clot",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/HRJ8l",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/HRJ8l.png"
                },
                {  
                    "id":"EhHkb",
                    "name":"Clotty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/EhHkb",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/EhHkb.png"
                },
                {  
                    "id":"J331A",
                    "name":"Cod Worm",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/J331A",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/J331A.png"
                },
                {  
                    "id":"EmDst",
                    "name":"Conjoined Fatty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/EmDst",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/EmDst.png"
                },
                {  
                    "id":"D4q0q",
                    "name":"Conjoined Spitty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/D4q0q",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/D4q0q.png"
                },
                {  
                    "id":"vuKDM",
                    "name":"Corn Dip",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/vuKDM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/vuKDM.png"
                },
                {  
                    "id":"bG5Lf",
                    "name":"Crazy Long Legs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/bG5Lf",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/bG5Lf.png"
                },
                {  
                    "id":"VKtsc",
                    "name":"Cyclopia",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/VKtsc",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/VKtsc.png"
                },
                {  
                    "id":"hYD2E",
                    "name":"Dank Death's Head",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/hYD2E",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/hYD2E.png"
                },
                {  
                    "id":"UtVjO",
                    "name":"Dank Globin",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/UtVjO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/UtVjO.png"
                },
                {  
                    "id":"N6WWA",
                    "name":"Dank Squirt",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/N6WWA",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/N6WWA.png"
                },
                {  
                    "id":"Rty6q",
                    "name":"Dart Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/Rty6q",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/Rty6q.png"
                },
                {  
                    "id":"zfQ6e",
                    "name":"Death's Head",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/zfQ6e",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/zfQ6e.png"
                },
                {  
                    "id":"mFJUH",
                    "name":"Dinga",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/mFJUH",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/mFJUH.png"
                },
                {  
                    "id":"mLE6V",
                    "name":"Dip",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/mLE6V",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/mLE6V.png"
                },
                {  
                    "id":"vOwTU",
                    "name":"Dople",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/vOwTU",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/vOwTU.png"
                },
                {  
                    "id":"VXPKR",
                    "name":"Double Vis",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/VXPKR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/VXPKR.png"
                },
                {  
                    "id":"abcAv",
                    "name":"Drowned Boom Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/abcAv",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/abcAv.png"
                },
                {  
                    "id":"KkLTR",
                    "name":"Drowned Charger",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/KkLTR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/KkLTR.png"
                },
                {  
                    "id":"Ucw2z",
                    "name":"Drowned Hive",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/Ucw2z",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/Ucw2z.png"
                },
                {  
                    "id":"DWmFO",
                    "name":"Dukie",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/DWmFO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/DWmFO.png"
                },
                {  
                    "id":"m5Qxu",
                    "name":"Embryo",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/m5Qxu",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/m5Qxu.png"
                },
                {  
                    "id":"ry7Ua",
                    "name":"Eternal Fly",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/ry7Ua",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/ry7Ua.png"
                }
            ]
        }

### Retrieve a Monster [GET /monster/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"3ot7Z",
                "name":"Attack Fly",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/monster/3ot7Z",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/monsters/3ot7Z.png"
            }

## Pickups [/pickup]

### List all Pickups [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":111,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup?page=3",
            "data":[  
                {  
                    "id":"xiV0L",
                    "name":"? Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/xiV0L",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/xiV0L.png"
                },
                {  
                    "id":"y0EUn",
                    "name":"???",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/y0EUn",
                    "sprite_url":null
                },
                {  
                    "id":"DMatY",
                    "name":"0 - The Fool",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/DMatY",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/DMatY.png"
                },
                {  
                    "id":"qw2x2",
                    "name":"1+1 Free Bomb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/qw2x2",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/qw2x2.png"
                },
                {  
                    "id":"nciX0",
                    "name":"1+1 Free Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/nciX0",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/nciX0.png"
                },
                {  
                    "id":"bpm1w",
                    "name":"1+1 Free Penny",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/bpm1w",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/bpm1w.png"
                },
                {  
                    "id":"lAyGY",
                    "name":"2 of Clubs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/lAyGY",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/lAyGY.png"
                },
                {  
                    "id":"mTMWK",
                    "name":"2 of Diamonds",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/mTMWK",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/mTMWK.png"
                },
                {  
                    "id":"c2qFX",
                    "name":"2 of Hearts",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/c2qFX",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/c2qFX.png"
                },
                {  
                    "id":"bjiAX",
                    "name":"2 of Spades",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/bjiAX",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/bjiAX.png"
                },
                {  
                    "id":"yCQA8",
                    "name":"48 Hour Energy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/yCQA8",
                    "sprite_url":null
                },
                {  
                    "id":"4CBm7",
                    "name":"A Card Against Humanity",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/4CBm7",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/4CBm7.png"
                },
                {  
                    "id":"xBA7M",
                    "name":"Addicted",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/xBA7M",
                    "sprite_url":null
                },
                {  
                    "id":"oRHRM",
                    "name":"Algiz",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/oRHRM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/oRHRM.png"
                },
                {  
                    "id":"LY1YH",
                    "name":"Amnesia",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/LY1YH",
                    "sprite_url":null
                },
                {  
                    "id":"dJt3Q",
                    "name":"Angel Chest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/dJt3Q",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/dJt3Q.png"
                },
                {  
                    "id":"3k3mJ",
                    "name":"Ansuz",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/3k3mJ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/3k3mJ.png"
                },
                {  
                    "id":"aLDjV",
                    "name":"Bad Gas",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/aLDjV",
                    "sprite_url":null
                },
                {  
                    "id":"p1fm5",
                    "name":"Bad Trip",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/p1fm5",
                    "sprite_url":null
                },
                {  
                    "id":"xfVxJ",
                    "name":"Balls of Steel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/xfVxJ",
                    "sprite_url":null
                },
                {  
                    "id":"L3BXI",
                    "name":"Berkano",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/L3BXI",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/L3BXI.png"
                },
                {  
                    "id":"52BBd",
                    "name":"Black Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/52BBd",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/52BBd.png"
                },
                {  
                    "id":"CRcm1",
                    "name":"Blank Rune",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/CRcm1",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/CRcm1.png"
                },
                {  
                    "id":"y8mEg",
                    "name":"Bomb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/y8mEg",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/y8mEg.png"
                },
                {  
                    "id":"1maGQ",
                    "name":"Bombs Are Key",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/1maGQ",
                    "sprite_url":null
                },
                {  
                    "id":"HkdeC",
                    "name":"Brown Chest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/HkdeC",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/HkdeC.png"
                },
                {  
                    "id":"H3UDb",
                    "name":"Chaos Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/H3UDb",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/H3UDb.png"
                },
                {  
                    "id":"8TZlC",
                    "name":"Credit Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/8TZlC",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/8TZlC.png"
                },
                {  
                    "id":"AiV0a",
                    "name":"Dagaz",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/AiV0a",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/AiV0a.png"
                },
                {  
                    "id":"6ggH4",
                    "name":"Dice Shard",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/6ggH4",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/6ggH4.png"
                },
                {  
                    "id":"Af0jY",
                    "name":"Dime",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/Af0jY",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/Af0jY.png"
                },
                {  
                    "id":"BtUoh",
                    "name":"Ehwaz",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/BtUoh",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/BtUoh.png"
                },
                {  
                    "id":"yA85P",
                    "name":"Emergency Contact",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/yA85P",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/yA85P.png"
                },
                {  
                    "id":"qYtzp",
                    "name":"Eternal Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/qYtzp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/qYtzp.png"
                },
                {  
                    "id":"16jky",
                    "name":"Explosive Diarrhea",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/16jky",
                    "sprite_url":null
                },
                {  
                    "id":"zpb06",
                    "name":"Friends Till The End!",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/zpb06",
                    "sprite_url":null
                },
                {  
                    "id":"Ayf44",
                    "name":"Full Health",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/Ayf44",
                    "sprite_url":null
                },
                {  
                    "id":"gUnNx",
                    "name":"Get Out Of Jail Free Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/gUnNx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/gUnNx.png"
                },
                {  
                    "id":"wPaF1",
                    "name":"Gold Bomb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/wPaF1",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/wPaF1.png"
                },
                {  
                    "id":"5Zwa4",
                    "name":"Gold Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/5Zwa4",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/5Zwa4.png"
                },
                {  
                    "id":"j2azR",
                    "name":"Golden Chest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/j2azR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/j2azR.png"
                },
                {  
                    "id":"rx7ei",
                    "name":"Golden Key",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/rx7ei",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/rx7ei.png"
                },
                {  
                    "id":"VLXAN",
                    "name":"Hagalaz",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/VLXAN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/VLXAN.png"
                },
                {  
                    "id":"xUuGo",
                    "name":"Half Red Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/xUuGo",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/xUuGo.png"
                },
                {  
                    "id":"lZyrt",
                    "name":"Health Down",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/lZyrt",
                    "sprite_url":null
                },
                {  
                    "id":"vGRIu",
                    "name":"Health Up",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/vGRIu",
                    "sprite_url":null
                },
                {  
                    "id":"Vc9lC",
                    "name":"Hematemesis",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/Vc9lC",
                    "sprite_url":null
                },
                {  
                    "id":"dG5cx",
                    "name":"I - The Magician",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/dG5cx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/dG5cx.png"
                },
                {  
                    "id":"xRcqJ",
                    "name":"I Can See Forever",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/xRcqJ",
                    "sprite_url":null
                },
                {  
                    "id":"Tw3t8",
                    "name":"I Found Pills",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/Tw3t8",
                    "sprite_url":null
                }
            ]
        }

### Retrieve a Pickup [GET /pickup/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"qYtzp",
                "name":"Eternal Heart",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pickup/qYtzp",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pickups/qYtzp.png"
            }

## Pill Appearances [/pill-appearance]

### List all Pill Appearances [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":13,
            "total":13,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance?page=1",
            "next":null,
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance?page=1",
            "data":[  
                {  
                    "id":"TtUz4",
                    "identifier":"black-yellow",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/TtUz4",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/TtUz4.png"
                },
                {  
                    "id":"7FqKv",
                    "identifier":"blue-blue",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/7FqKv",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/7FqKv.png"
                },
                {  
                    "id":"SaB0y",
                    "identifier":"orange-orange",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/SaB0y",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/SaB0y.png"
                },
                {  
                    "id":"ekzWv",
                    "identifier":"pink-red",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/ekzWv",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/ekzWv.png"
                },
                {  
                    "id":"Paigw",
                    "identifier":"red-speckled-red",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/Paigw",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/Paigw.png"
                },
                {  
                    "id":"yzsO8",
                    "identifier":"speckled-orange-white",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/yzsO8",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/yzsO8.png"
                },
                {  
                    "id":"uTeYC",
                    "identifier":"violet-cyan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/uTeYC",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/uTeYC.png"
                },
                {  
                    "id":"hhG1e",
                    "identifier":"white-black",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/hhG1e",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/hhG1e.png"
                },
                {  
                    "id":"M3FPw",
                    "identifier":"white-blue",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/M3FPw",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/M3FPw.png"
                },
                {  
                    "id":"kNVz8",
                    "identifier":"white-cyan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/kNVz8",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/kNVz8.png"
                },
                {  
                    "id":"xyes3",
                    "identifier":"white-white",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/xyes3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/xyes3.png"
                },
                {  
                    "id":"bVnYx",
                    "identifier":"white-yellow",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/bVnYx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/bVnYx.png"
                },
                {  
                    "id":"vxiPT",
                    "identifier":"yellow-orange",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/vxiPT",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/vxiPT.png"
                }
            ]
        }

### Retrieve a Pill Appearance [GET /pill-appearance/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id":"TtUz4",
                "identifier":"black-yellow",
                "url":"https://isaac.jamesmcfadden.co.uk/api/v1/pill-appearance/TtUz4",
                "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/pill-appearances/TtUz4.png"
            }
