FORMAT: 1A
HOST: https://isaac.jamesmcfadden.co.uk/api/v1

# Binding of Isaac API

Documentation for the Open Source Binding of Isaac RESTful API.

The source code is hosted at [https://github.com/jamesmcfadden/binding-of-isaac-api](https://github.com/jamesmcfadden/binding-of-isaac-api).

**Note that the API is still in early development, so breaking changes can, and most likely will, happen.**

## Items [/item]

### List all Items [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":438,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/item?page=9",
            "data":[  
                {  
                    "id":"c12kq",
                    "name":"???'s Only Friend",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/c12kq",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/c12kq.png"
                },
                {  
                    "id":"gGBZ0",
                    "name":"<3",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/gGBZ0",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ggbz0.png"
                },
                {  
                    "id":"Fi7wn",
                    "name":"1up!",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/Fi7wn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fi7wn.png"
                },
                {  
                    "id":"5eMPp",
                    "name":"20/20",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/5eMPp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/5empp.png"
                },
                {  
                    "id":"xp9U9",
                    "name":"3 Dollar Bill",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/xp9U9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/xp9u9.png"
                },
                {  
                    "id":"y7NCo",
                    "name":"8 Inch Nails",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/y7NCo",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/y7nco.png"
                },
                {  
                    "id":"GGxkj",
                    "name":"9 Volt",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/GGxkj",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ggxkj.png"
                },
                {  
                    "id":"YHhYP",
                    "name":"A Dollar",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/YHhYP",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/yhhyp.png"
                },
                {  
                    "id":"pYWTI",
                    "name":"A Lump Of Coal",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/pYWTI",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/pywti.png"
                },
                {  
                    "id":"fXgdx",
                    "name":"A Quarter",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fXgdx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fxgdx.png"
                },
                {  
                    "id":"CraPZ",
                    "name":"A Snack",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/CraPZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/crapz.png"
                },
                {  
                    "id":"wvkEw",
                    "name":"Abaddon",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/wvkEw",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wvkew.png"
                },
                {  
                    "id":"TGsYa",
                    "name":"Abel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/TGsYa",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/tgsya.png"
                },
                {  
                    "id":"hz3cQ",
                    "name":"Anarchist Cookbook",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/hz3cQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hz3cq.png"
                },
                {  
                    "id":"eOTdf",
                    "name":"Anemic",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/eOTdf",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/eotdf.png"
                },
                {  
                    "id":"iUbbQ",
                    "name":"Ankh",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/iUbbQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/iubbq.png"
                },
                {  
                    "id":"iSdFu",
                    "name":"Anti-Gravity",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/iSdFu",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/isdfu.png"
                },
                {  
                    "id":"On84I",
                    "name":"Aquarius",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/On84I",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/on84i.png"
                },
                {  
                    "id":"rEky9",
                    "name":"Aries",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/rEky9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/reky9.png"
                },
                {  
                    "id":"D9B0M",
                    "name":"Athame",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/D9B0M",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/d9b0m.png"
                },
                {  
                    "id":"KQnUV",
                    "name":"Ball Of Bandages",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/KQnUV",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/kqnuv.png"
                },
                {  
                    "id":"EmDst",
                    "name":"Ball Of Tar",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EmDst",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/emdst.png"
                },
                {  
                    "id":"l74LW",
                    "name":"BBF",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/l74LW",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/l74lw.png"
                },
                {  
                    "id":"IbtH7",
                    "name":"Best Bud",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/IbtH7",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ibth7.png"
                },
                {  
                    "id":"esTBU",
                    "name":"Best Friend",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/esTBU",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/estbu.png"
                },
                {  
                    "id":"o9S30",
                    "name":"Betrayal",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/o9S30",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/o9s30.png"
                },
                {  
                    "id":"EdMbD",
                    "name":"BFFS!",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EdMbD",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/edmbd.png"
                },
                {  
                    "id":"Eipw9",
                    "name":"Big Fan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/Eipw9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/eipw9.png"
                },
                {  
                    "id":"wyQgx",
                    "name":"Binky",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/wyQgx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wyqgx.png"
                },
                {  
                    "id":"UtVjO",
                    "name":"Black Candle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/UtVjO",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/utvjo.png"
                },
                {  
                    "id":"jLia3",
                    "name":"Black Lotus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/jLia3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/jlia3.png"
                },
                {  
                    "id":"xmxnZ",
                    "name":"Black Powder",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/xmxnZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/xmxnz.png"
                },
                {  
                    "id":"B4Vbz",
                    "name":"Blank Card",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/B4Vbz",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/b4vbz.png"
                },
                {  
                    "id":"9haGF",
                    "name":"Blood Bag",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/9haGF",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/9hagf.png"
                },
                {  
                    "id":"c5PfF",
                    "name":"Blood Clot",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/c5PfF",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/c5pff.png"
                },
                {  
                    "id":"WMiun",
                    "name":"Blood Of The Martyr",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/WMiun",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/wmiun.png"
                },
                {  
                    "id":"fPRsJ",
                    "name":"Blood Rights",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fPRsJ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fprsj.png"
                },
                {  
                    "id":"oxgoK",
                    "name":"Bloody Lust",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/oxgoK",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/oxgok.png"
                },
                {  
                    "id":"72Dht",
                    "name":"Blue Cap",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/72Dht",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/72dht.png"
                },
                {  
                    "id":"EhHkb",
                    "name":"Blue Map",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/EhHkb",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/ehhkb.png"
                },
                {  
                    "id":"HRJ8l",
                    "name":"Bob's Brain",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/HRJ8l",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hrj8l.png"
                },
                {  
                    "id":"DrwHN",
                    "name":"Bob's Curse",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/DrwHN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/drwhn.png"
                },
                {  
                    "id":"1quq3",
                    "name":"Bob's Rotten Head",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/1quq3",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/1quq3.png"
                },
                {  
                    "id":"HlFtG",
                    "name":"Bobby-Bomb",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/HlFtG",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/hlftg.png"
                },
                {  
                    "id":"GBwDx",
                    "name":"Bogo Bombs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/GBwDx",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/gbwdx.png"
                },
                {  
                    "id":"J71v7",
                    "name":"Bomb Bag",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/J71v7",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/j71v7.png"
                },
                {  
                    "id":"3W0mR",
                    "name":"Bomber Boy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/3W0mR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/3w0mr.png"
                },
                {  
                    "id":"fv4EL",
                    "name":"Book Of Revelations",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/fv4EL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/fv4el.png"
                },
                {  
                    "id":"LMCDe",
                    "name":"Book Of Secrets",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/LMCDe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/lmcde.png"
                },
                {  
                    "id":"KOPsZ",
                    "name":"Book Of Shadows",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/item/KOPsZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/items/kopsz.png"
                }
            ]
        }

### Retrieve an Item [GET /item/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id": "2JrEs",
                "name": "Pentagram",
                "url": "https://isaac.jamesmcfadden.co.uk/api/v1/item/2JrEs",
                "sprite_url": "http://boi-api.dev/img/sprites/items/2jres.png"
            }

## Bosses [/boss]

### List all Bosses [GET]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {  
            "count":50,
            "total":83,
            "first":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=1",
            "next":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=2",
            "previous":null,
            "last":"https://isaac.jamesmcfadden.co.uk/api/v1/boss?page=2",
            "data":[  
                {  
                    "id":"xWPxL",
                    "name":"Blastocyst",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/xWPxL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/xwpxl.png"
                },
                {  
                    "id":"3ot7Z",
                    "name":"Blue Baby",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/3ot7Z",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/3ot7z.png"
                },
                {  
                    "id":"iK4uM",
                    "name":"Brownie",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/iK4uM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ik4um.png"
                },
                {  
                    "id":"Rty6q",
                    "name":"C.H.A.D.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Rty6q",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/rty6q.png"
                },
                {  
                    "id":"pfj4n",
                    "name":"Chub",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/pfj4n",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/pfj4n.png"
                },
                {  
                    "id":"YaF7j",
                    "name":"Conquest",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/YaF7j",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/yaf7j.png"
                },
                {  
                    "id":"ry7Ua",
                    "name":"Daddy Long Legs",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/ry7Ua",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ry7ua.png"
                },
                {  
                    "id":"ufpUE",
                    "name":"Dangle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/ufpUE",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ufpue.png"
                },
                {  
                    "id":"YaGZp",
                    "name":"Dark One",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/YaGZp",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/yagzp.png"
                },
                {  
                    "id":"LMCDe",
                    "name":"Death",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/LMCDe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/lmcde.png"
                },
                {  
                    "id":"gs6UX",
                    "name":"Dingle",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/gs6UX",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gs6ux.png"
                },
                {  
                    "id":"plQUT",
                    "name":"Envy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/plQUT",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/plqut.png"
                },
                {  
                    "id":"Bzoer",
                    "name":"Famine",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Bzoer",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bzoer.png"
                },
                {  
                    "id":"p7mbN",
                    "name":"Fistula",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/p7mbN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/p7mbn.png"
                },
                {  
                    "id":"gZVST",
                    "name":"Gabriel",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/gZVST",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gzvst.png"
                },
                {  
                    "id":"7GFNZ",
                    "name":"Gemini",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/7GFNZ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/7gfnz.png"
                },
                {  
                    "id":"mLE6V",
                    "name":"Gish",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/mLE6V",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/mle6v.png"
                },
                {  
                    "id":"vuKDM",
                    "name":"Gluttony",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/vuKDM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/vukdm.png"
                },
                {  
                    "id":"Jv6Mk",
                    "name":"Greed",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Jv6Mk",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/jv6mk.png"
                },
                {  
                    "id":"N6WWA",
                    "name":"Gurdy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/N6WWA",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/n6wwa.png"
                },
                {  
                    "id":"mFJUH",
                    "name":"Gurdy Jr.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/mFJUH",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/mfjuh.png"
                },
                {  
                    "id":"yKfJS",
                    "name":"Gurglings",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/yKfJS",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ykfjs.png"
                },
                {  
                    "id":"KruQ8",
                    "name":"Hush",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/KruQ8",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/kruq8.png"
                },
                {  
                    "id":"F5Ta0",
                    "name":"Isaac",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/F5Ta0",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/f5ta0.png"
                },
                {  
                    "id":"PJ6Pl",
                    "name":"It Lives",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/PJ6Pl",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/pj6pl.png"
                },
                {  
                    "id":"VKq9n",
                    "name":"Krampus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/VKq9n",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/vkq9n.png"
                },
                {  
                    "id":"icZ0S",
                    "name":"Larry Jr.",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/icZ0S",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/icz0s.png"
                },
                {  
                    "id":"AFvzN",
                    "name":"Little Horn",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/AFvzN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/afvzn.png"
                },
                {  
                    "id":"bG5Lf",
                    "name":"Loki",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/bG5Lf",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bg5lf.png"
                },
                {  
                    "id":"GJgId",
                    "name":"Lokii",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/GJgId",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/gjgid.png"
                },
                {  
                    "id":"fv7EQ",
                    "name":"Lust",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/fv7EQ",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fv7eq.png"
                },
                {  
                    "id":"TOwix",
                    "name":"Mama Gurdy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/TOwix",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/towix.png"
                },
                {  
                    "id":"FHsB6",
                    "name":"Mask of Infamy",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/FHsB6",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fhsb6.png"
                },
                {  
                    "id":"af31L",
                    "name":"Mega Fatty",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/af31L",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/af31l.png"
                },
                {  
                    "id":"6m78r",
                    "name":"Mega Maw",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/6m78r",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/6m78r.png"
                },
                {  
                    "id":"i0vFD",
                    "name":"Mega Satan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/i0vFD",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/i0vfd.png"
                },
                {  
                    "id":"PHIeR",
                    "name":"Mom",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/PHIeR",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/phier.png"
                },
                {  
                    "id":"BmmeN",
                    "name":"Mom's Heart",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/BmmeN",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/bmmen.png"
                },
                {  
                    "id":"qVIN9",
                    "name":"Monstro",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/qVIN9",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qvin9.png"
                },
                {  
                    "id":"TswBe",
                    "name":"Monstro II",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/TswBe",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/tswbe.png"
                },
                {  
                    "id":"GA8TG",
                    "name":"Mr. Fred",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/GA8TG",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ga8tg.png"
                },
                {  
                    "id":"Ii7MK",
                    "name":"Peep",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/Ii7MK",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/ii7mk.png"
                },
                {  
                    "id":"twGCn",
                    "name":"Pestilence",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/twGCn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/twgcn.png"
                },
                {  
                    "id":"fa6Ly",
                    "name":"Pin",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/fa6Ly",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/fa6ly.png"
                },
                {  
                    "id":"0ug2s",
                    "name":"Polycephalus",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/0ug2s",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/0ug2s.png"
                },
                {  
                    "id":"banyC",
                    "name":"Pride",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/banyC",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/banyc.png"
                },
                {  
                    "id":"xjnFL",
                    "name":"Rag Man",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/xjnFL",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/xjnfl.png"
                },
                {  
                    "id":"QkpIn",
                    "name":"Satan",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/QkpIn",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qkpin.png"
                },
                {  
                    "id":"qzFxM",
                    "name":"Scolex",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/qzFxM",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qzfxm.png"
                },
                {  
                    "id":"bTCYd",
                    "name":"Sloth",
                    "url":"https://isaac.jamesmcfadden.co.uk/api/v1/boss/bTCYd",
                    "sprite_url":"https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/btcyd.png"
                }
            ]
        }

### Retrieve a Boss [GET /boss/{id}]

+ Request

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "id": "qVIN9",
                "name": "Monstro",
                "url": "https://isaac.jamesmcfadden.co.uk/api/v1/boss/qVIN9",
                "sprite_url": "https://isaac.jamesmcfadden.co.uk/img/sprites/bosses/qVIN9.png"
            }
